### ISSUE TITLE
Planned support for playback/multimedia keys? 

### ISSUE THREAD

**Issue by pawlik** [jooapa/jammer#66]
**Describe the bug**
I love the tool <3, do you plan on adding support for multimedia keys from keyboards? You know - play/pause; next, prev, you know - those: 

![PXL_20240503_070235626](https://github.com/jooapa/jammer/assets/61051/b98a9897-eaf8-413d-b5f4-545f58f58862)

**To Reproduce**
1. start a playlist
2. hit pause - nothing happens
3. het prev/next - nothing happens

**Expected behavior**
Hitting pause - pauses the playback, hittin play - starts it. etc .

**Screenshots**

**Desktop (please complete the following information):**
```
$ uname -a
Linux pop-os 6.8.0-76060800daily20240311-generic #202403110203~1713206908~22.04~3a62479 SMP PREEMPT_DYNAMIC Mon A x86_64 GNU/Linux
```

**Comment by Antonako1** [comment]
I'm on my way, partner
![200w](https://github.com/jooapa/jammer/assets/114558368/1fb080bd-acef-4ddd-bdbb-280829fb9851)

**Comment by Antonako1** [comment]
Feature added: [https://github.com/jooapa/jammer/releases/tag/2.1.0.1](https://github.com/jooapa/jammer/releases/tag/2.1.0.1)

**Comment by pawlik** [comment]
Works like a charm! :tada: :tada: :tada: 
How can I buy you coffee?

**Comment by Antonako1** [comment]
Good to hear! And no need to buy coffees for me :)
