### ISSUE TITLE
[Linux] Local files won't play if there are spaces in the filename

### ISSUE THREAD

**Issue by soner89** [jooapa/jammer#71]
**Describe the bug**
When you want to play a local mp3 file from your local drive and the filename has spaces in it, jammer won't play them.

**To Reproduce**
1. Rename an mp3 file so it has spaces in it. Example: 01 Title Song.mp3
2. Pass the mp3 file to jammer like this: $ jammer 01\ Title\ Song.mp3

The error should be visible now.

**Expected behavior**
The expectation is that local files with spaces in their names will be played the same way as files without spaces in their names.

**Screenshots**
![image](https://github.com/jooapa/jammer/assets/3781642/80e4b89f-4cae-4bc7-bb8d-ef03b0dbf155)

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Jammer version 2.2.3.4

**Comment by soner89** [comment]
> I would suggest you using quotes in the arguments. any terminal should autocomplete the file to the quote format
> 
> ```
> jammer 01\ Title\ Song.mp3 
> ->
> jammer "01 Title Song.mp3"
> ```

Thanks for the suggestion, I already tried that but didn't mention it:

![image](https://github.com/jooapa/jammer/assets/3781642/5c4faedf-066c-4b45-9436-6a4c6d39b6e2)

I even tried another shell, which shouldn't have any effect but still it didn't play the songs. However, I can play songs without spaces in the filenames.

**Comment by Antonako1** [comment]
Is this still a problem in the latest release?

**Comment by soner89** [comment]
> Is this still a problem in the latest release?

Just downloaded the latest source (2.7.12.13) and built an AppImage with the build.sh script. I used that appimage to open an mp3 file with spaces in it, I still get the same error.

In short: Yes, it seems to be still a problem in the latest release.

Am I the only one with this issue? :smile:

**Comment by Antonako1** [comment]
Oh yeah, I tried it myself using the executable, not the appimage :DDD but got it fixed, the argument passing in the appimage script was invalid. I'll get the new version published as soon as possible :)

**Comment by Antonako1** [comment]
Try out the latest release, let me know if the problem continues :)

**Comment by soner89** [comment]
> Try out the latest release, let me know if the problem continues :)

Thank you, I just tried version 2.8.1.2 and I can play now songs with spaces in them!

Very appreciated, it's an awesome app!!
