### ISSUE TITLE
mp3PRO files playing as normal mp3's

### ISSUE THREAD

**Issue by 256shadesofgrey** [jooapa/jammer#86]
**Describe the bug**
The README claims that jammer supports mp3PRO (which is why I downloaded it in the first place), but when I play a song that is encoded in mp3PRO, the "PRO" part (i.e. SBR) is ignored and none of the frequencies above about 10kHz are playing (see screenshot below). If I play the same track via wine in WinAmp with the mp3PRO plugin or with JetAudio, the frequencies are present and it sounds "brighter" as one would expect when frequencies up to at least 16kHz are added.

Since mp3PRO is basically an abandoned format and you may have difficulty finding software that can still encode it, [here is an archive containing 3 audio files with white noise](https://github.com/user-attachments/files/16355108/white-noise.zip) for testing purposes where the difference is very obvious. `white-noise-original.flac` is the source file that I generated before transcoding to mp3PRO. `white-noise.mp3` was then created by transcoding the original .flac file into mp3PRO, and `white-noise.flac` was created by converting the mp3PRO file back to flac. Because flac is a lossless format, `white-noise.mp3` and `white-noise.flac` should sound identical, and they do via WinAmp+plugin and via JetAudio, but do not via jammer (or VLC which I used as a comparison for a player that supports mp3 but not mp3PRO).

**To Reproduce**
1. Download the appimage.
2. Add execution permissions to the appimage: `chmod +x ./jammer-2.11.2.2-x86_64.appimage`
3. Play an audio file encoded in mp3PRO `./jammer-2.11.2.2-x86_64.appimage white-noise.mp3`
4. Listen and hear the high frequencies missing.

**Expected behavior**
The track should play with all the frequencies that would be present when the song is played on a player with mp3PRO support.

**Screenshots**
Here I have played the included white noise files while using a spectrum analyzer app on my phone. You see 4 blocks of audio. From the bottom to the top it's the original flac played in JetAudio, then the mp3PRO played in JetAudio, then the converted flac played in JetAudio, and the last block at the top where everything over 10kHz is missing is the mp3PRO played in jammer.
![Spectrum analyzer](https://github.com/user-attachments/assets/058a94b9-0432-4f6a-aa1d-1fb694b5f734)

**Desktop (please complete the following information):**
 - OS: Linux 6.9.10-arch1-1 (EndeavourOS)

**Comment by jooapa** [comment]
after some research bass the library cannot play mp3pro files at all, no idea why I had it listed as one of the playable formats :/
https://github.com/jooapa/jammer/commit/ddfaca14c7c173f67c8e3acd1eb5fa4dd50229f0
