### ISSUE TITLE
add a search/filter/fuzzy-match option for the current playlist?

### ISSUE THREAD

**Issue by gotbletu** [jooapa/jammer#90]
**Describe the cool new thing you'd like to see in Jammer**

I check the hotkeys list but don't see anyway to search the current local playlist for keyword.

could you add a way to search/filter/or fuzzy-match the current list of tracks on the playlist?
I just need to jump quickly to my local midi/mp3 files.
Because moving up and down with the pageup/down hotkey is slow if u got like 1000s songs.
Its pretty standard on all music players. usually on linux and most text editors is the '/' hotkey

**Comment by jooapa** [comment]
new 3.0 release use F3 key to fuzzy search current playlist
