### ISSUE TITLE
Duplicate lines

### ISSUE THREAD

**Issue by TheDrone7** [jooapa/jammer#95]
**Describe the bug**
In the player's UI, there is a duplicate line (that does not update) with the pause, shuffle, and the rest of the indicators (slightly annoying/confusing to look at)

This is only seen when music is playing, its fine when the music is paused.

**To Reproduce**
1. Pick a YouTube playlist to play, I chose https://youtube.com/playlist?list=PL6FCrUlKUbA3zDx6AlZbffv0MdEp9dMn0&si=TFwFqniAirsCVt3P
2. Run `jammer <playlist-url>` in the terminal.
3. See error

**Expected behavior**
A clean UI

**Screenshots**
![image](https://github.com/user-attachments/assets/1ef0614f-c0a0-472f-a2a5-ea3f3bb09d42)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Jammer version 3.0.0.0

**Comment by jooapa** [comment]
I just cant for the life of me replicate this bug.. I have tried pretty much everything

**Comment by TheDrone7** [comment]
Haven't tested it and it might just be my guess, but have you tried the `foot` terminal? That's the only thing I can think of that I did not mention initially.

**Comment by TheDrone7** [comment]
I only added the Catppuccin theme and a custom font on foot terminal on top of the defaults, pretty sure that can't mess this up but I will give it a try with default config as well just to confirm.

**Comment by TheDrone7** [comment]
Unfortunately, still persists with the defaults for foot
![image](https://github.com/user-attachments/assets/ba84b1cf-1677-4d3c-b247-3e4adfe80de0)

Again, only happens with foot and not with kitty's or alacritty's defaults.
