### ISSUE TITLE
doesnt play playlist

### ISSUE THREAD

**Issue by MIPOHBOPOHIH** [jooapa/jammer#97]
**Describe the bug**
after install i cant play my playlist

**To Reproduce**
1. install jammer on windows
2. `jammer https://soundcloud.com/winet-132118884/sets/faken-sh1t`
3.  crash 

**Screenshots**
![image](https://github.com/user-attachments/assets/5800791e-efa4-4167-9195-8c831c1af3da)

**Desktop (please complete the following information):**
 - OS: windows

**Comment by Antonako1** [comment]
try adding clientid to "%userprofile%\jammer\settings.json" or press "shift + alt + 1". [https://github.com/jooapa/jammer?tab=readme-ov-file#soundcloud](https://github.com/jooapa/jammer?tab=readme-ov-file#soundcloud)
